### ISSUE TITLE
Sign in and Sign up UI

### ISSUE THREAD

**Issue by opw0011** [mkmooltham/BPS#5]
@mkmooltham 
1. Fix the sign in and sign up button
original the two page use the same switch button. I split it into standalone sign in and sign up
Please work with the layout
![default](https://cloud.githubusercontent.com/assets/10897048/22680219/d388a76c-ed41-11e6-9313-2e93e1a83edf.png)

2. Add email input field in sign up page
As Parse required email to sign up

**Comment by mkmooltham** [comment]
will modify it today
